### PR TITLE
Consider also "maven.surefire.debug" environment variable while decid…

### PR DESCRIPTION
**Pull request by skivol**
…ing if we are debugging

* to make debugging a more seamless process if started from command line using `maven`.

### CODE REVIEW

**Comment by splitfeed** [comment]
I don't know if or how you can verify the codecov checks without pushing, but the failing tests are due to some flakyness. I reported one of these in #70, but it doesn't seem to be limited to that single test any longer.

**Comment by skivol** [comment]
Can we run the tests once again? :)

**Comment by skivol** [comment]
Any ideas on how to make "codecov/patch" happy? (don't know if https://github.com/kata-containers/tests/issues/508 suggest a proper approach, but anyway :) )

**Comment by splitfeed** [comment]
It looks strange, the coverage seems good to me. I'll just merge this :)

**Comment by skivol** [comment]
Thanks :)

**Comment by skivol** [comment]
@splitfeed, so when is the next release? :)

**Pull request merged**
