### PR TITLE
Update Mockito from 1.10.16 to 3.1.0

### PR DESCRIPTION
**Pull request by linsnos**
... and depending bytebuddy from 1.9.3 to 1.10.3.

### CODE REVIEW

**Comment by flowertwig** [comment]
The mockito api has changed, so this will force changes. Just so we're aware.

**Comment by flowertwig** [comment]
Also, some matching behaviour has changed, i.e. anyX and any(class).

**Comment by JonasHallFnx** [comment]
> Also, some matching behaviour has changed, i.e. anyX and any(class).

@flowertwig Do you propose we upgrade to a lower version? The upgrade was needed to support mocking of internal Auth class having interface with default implementation, which is supported in version 2+.

**Comment by flowertwig** [comment]
> > Also, some matching behaviour has changed, i.e. anyX and any(class).
> 
> @flowertwig Do you propose we upgrade to a lower version? The upgrade was needed to support mocking of internal Auth class having interface with default implementation, which is supported in version 2+.

No. The upgrade is long overdue and I'm pretty sure the biggest difference is between 1 and 2 anyway. We just need to be aware that there will be compilation failures and probably some failing tests.

**Comment by rassmate** [comment]
Mockito has been upgraded in another pr. Closing this one

**Pull request closed without merging**
