### PR TITLE
Add support for List of UUIDs as a parameter for DAO methods

### PR DESCRIPTION
**Pull request by skivol**

### CODE REVIEW

**Comment by skivol** [comment]
Done :)

**Comment by splitfeed** [comment]
The build is failing, did you merge master?

**Comment by skivol** [comment]
No, will check.

**Comment by skivol** [comment]
Local `clean install` seemed to work, but looking closer at the error logs there is:
"ERROR[m] Failed to execute goal [32morg.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar[m [1m(default-cli)[m on project [36mreactivewizard-parent[m: [1;31mYou're not authorized to run analysis. Please contact the project administrator"
Something related to missing SonarQube permissions ?

**Comment by skivol** [comment]
@splitfeed, so is there anything else I can do about:

[[1;31mERROR[m] Failed to execute goal [32morg.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar[m [1m(default-cli)[m on project [36mreactivewizard-parent[m: [1;31mYou're not authorized to run analysis. Please contact the project administrator.[m -> [1m[Help 1][m

error ?

**Comment by splitfeed** [comment]
I just realized that this might be because you are creating a PR from a fork. I don't really know how to solve this atm, but the code builds so I say we just go ahead and merge 👍

**Comment by skivol** [comment]
@splitfeed, @JonasHallFnx somebody with merge permissions is needed I guess at this point :)

**Pull request merged**
